### ISSUE TITLE
nested brightness shouldn't be preserved

### ISSUE THREAD

**Issue by tmx976** [medikoo/cli-color#30] opened 2016-11-17 10:59 UTC
adding the last two line to your sample code `basic.js`

```js
console.log('Styled text can be nested:');
console.log(clc.red('red ' + clc.blue('blue') + ' red'));
console.log(clc.red('red ' + clc.blueBright('blue') + ' red bright')+clc.yellow(' bright?'));
console.log(clc.redBright('red ') + ' bright?');
```

In the third line, the "red bright" piece of string appear red bright, but it shouldn't.. IMHO
the yellow one appear just yellow, as it should be.

Also the last default part of last line appear not bright, as it should be.

Seems that brihtness isn't cleared in close sequence when nested.

*I'm using (and I have to use) the standard windows cmd*

![image](https://cloud.githubusercontent.com/assets/13355520/20386694/0a077702-acbd-11e6-94f9-f5dc0327fd2e.png)

**Comment by medikoo** [comment] 2016-11-19 17:36
@tmx976 Which version of Node.js you're using. We had similar problem a longer while ago, and it was in fact Node.js bug -> https://github.com/nodejs/node-v0.x-archive/issues/4019

**Comment by medikoo** [comment] 2016-11-19 17:38
Looks as duplicate of https://github.com/medikoo/cli-color/issues/4 but let's confirm on your Node.js version

**Comment by medikoo** [comment] 2017-11-09 08:04
I'm closing it due to lack of test case that can confirm the issue

**Closed by medikoo** 2017-11-09 08:04 UTC
