### ISSUE TITLE
Problem testing the "throbber"

### ISSUE THREAD

**Issue by rentalhost** [medikoo/cli-color#19] opened 2015-03-18 19:11 UTC
When I run `npm test` it works with 99.65% of tests, but `throbber.js` fails.

    throbber.js
    Error: spawn UNKNOWN
        at exports._errnoException (util.js:746:11)
        at ChildProcess.spawn (child_process.js:1155:11)
        at exports.spawn (child_process.js:988:9)
        at module.exports. (D:\projects\cli-color\test\throbber.js:10:11)
        at D:\projects\cli-color\node_modules\tad\lib\run.js:71:7
        at Object.Reduce.processCb (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:101:18)
        at Object.Reduce [as continue] (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:67:18)
        at Object.Reduce.init (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:59:16)
        at Object.Reduce (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:39:14)
        at Array.module.exports (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:143:9)
        at run (D:\projects\cli-color\node_modules\tad\lib\run.js:39:18)
        at D:\projects\cli-color\node_modules\tad\lib\run.js:106:7
           
        at process._tickCallback (node.js:355:11)16:06:50.558  -  throbber.js: Formatted
    Error: spawn UNKNOWN
        at exports._errnoException (util.js:746:11)
        at ChildProcess.spawn (child_process.js:1155:11)
        at exports.spawn (child_process.js:988:9)
        at module.exports.Formatted (D:\projects\cli-color\test\throbber.js:27:11)
        at D:\projects\cli-color\node_modules\tad\lib\run.js:71:7
        at Object.Reduce.processCb (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:101:18)
        at Object.Reduce [as continue] (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:67:18)
        at Object.Reduce.init (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:59:16)
        at Object.Reduce (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:39:14)
        at Array.module.exports (D:\projects\cli-color\node_modules\tad\node_modules\deferred\ext\array\reduce.js:143:9)
        at run (D:\projects\cli-color\node_modules\tad\lib\run.js:39:18)
        at D:\projects\cli-color\node_modules\tad\lib\run.js:106:7
           
        at process._tickCallback (node.js:355:11)

I'm running on Windows 8.1.

    ├── d@0.1.1
    ├─┬ es5-ext@0.10.6
    │ ├── es6-iterator@0.1.3
    │ └── es6-symbol@2.0.1
    ├─┬ memoizee@0.3.8
    │ ├─┬ es6-weak-map@0.1.2
    │ │ ├─┬ es6-iterator@0.1.3
    │ │ │ └── es6-symbol@2.0.1
    │ │ └── es6-symbol@0.1.1
    │ ├── event-emitter@0.3.3
    │ ├── lru-queue@0.1.0
    │ └── next-tick@0.2.2
    ├─┬ tad@0.2.2
    │ ├── cli-color@0.3.2
    │ ├─┬ deferred@0.7.2
    │ │ └── next-tick@0.2.2
    │ ├── duration@0.2.0
    │ ├── event-emitter@0.3.3
    │ ├─┬ fs2@0.2.1
    │ │ └─┬ minimatch@0.2.14
    │ │   ├── lru-cache@2.5.0
    │ │   └── sigmund@1.0.0
    │ ├── next@0.4.0
    │ ├─┬ optimist@0.6.1
    │ │ ├── minimist@0.0.10
    │ │ └── wordwrap@0.0.2
    │ ├── path2@0.1.0
    │ └─┬ test@0.6.0
    │   └── ansi-font@0.0.2
    ├─┬ timers-ext@0.1.0
    │ └── next-tick@0.2.2
    ├─┬ xlint@0.2.2
    │ ├── cli-color@0.3.2
    │ ├─┬ deferred@0.7.2
    │ │ └── next-tick@0.2.2
    │ ├── event-emitter@0.3.3
    │ ├─┬ fs2@0.2.1
    │ │ └─┬ minimatch@0.2.14
    │ │   ├── lru-cache@2.5.0
    │ │   └── sigmund@1.0.0
    │ ├── next@0.4.0
    │ ├─┬ optimist@0.3.7
    │ │ └── wordwrap@0.0.2
    │ └── path2@0.1.0
    └─┬ xlint-jslint-medikoo@0.1.2
      └── xlint-jslint@0.1.0

**Comment by medikoo** [comment] 2015-03-20 15:09
It was caused by improper spawn usage. Should be fixed now, also published as v0.3.3. Thanks!

**Closed** 2015-03-20 15:08 UTC
Labels: bug

**Comment by rentalhost** [comment] 2015-03-20 15:22
Works perfectly now. :) Thanks!
